name: crud
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
